apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    persistence false
    log_dest stdout
    log_type all
    allow_anonymous false
    password_file /mosquitto/config/passwordfile.txt
    bind_address 0.0.0.0
